// Code generated by fixgen. DO NOT EDIT.

package fix44

// Enum type EnumQuoteCondition
const (
	EnumQuoteConditionOpen       string = "A"
	EnumQuoteConditionClosed     string = "B"
	EnumQuoteConditionExchbest   string = "C"
	EnumQuoteConditionConsolbest string = "D"
	EnumQuoteConditionLocked     string = "E"
	EnumQuoteConditionCrossed    string = "F"
	EnumQuoteConditionDepth      string = "G"
	EnumQuoteConditionFast       string = "H"
	EnumQuoteConditionNonfirm    string = "I"
)
