// Code generated by fixgen. DO NOT EDIT.

package fix44

// Enum type EnumApplQueueResolution
const (
	EnumApplQueueResolutionNoactiontaken string = "0"
	EnumApplQueueResolutionQueueflushed  string = "1"
	EnumApplQueueResolutionOverlaylast   string = "2"
	EnumApplQueueResolutionEndsession    string = "3"
)
