// Code generated by fixgen. DO NOT EDIT.

package fix44

// Enum type EnumProduct
const (
	EnumProductAgency      string = "1"
	EnumProductMortgage    string = "10"
	EnumProductMunicipal   string = "11"
	EnumProductOther       string = "12"
	EnumProductFinancing   string = "13"
	EnumProductCommodity   string = "2"
	EnumProductCorporate   string = "3"
	EnumProductCurrency    string = "4"
	EnumProductEquity      string = "5"
	EnumProductGovernment  string = "6"
	EnumProductIndex       string = "7"
	EnumProductLoan        string = "8"
	EnumProductMoneymarket string = "9"
)
