package fix44

// Enum type: EnumExecInst
const (
	EnumExecInstStayoffer            string = "0"
	EnumExecInstNotheld              string = "1"
	EnumExecInstWork                 string = "2"
	EnumExecInstGoalong              string = "3"
	EnumExecInstOverday              string = "4"
	EnumExecInstHeld                 string = "5"
	EnumExecInstPartnotinit          string = "6"
	EnumExecInstStrictscale          string = "7"
	EnumExecInstTrytoscale           string = "8"
	EnumExecInstStaybid              string = "9"
	EnumExecInstNocross              string = "A"
	EnumExecInstTrailstoppeg         string = "a"
	EnumExecInstOkcross              string = "B"
	EnumExecInstStrictlimit          string = "b"
	EnumExecInstIgnorepricechk       string = "c"
	EnumExecInstCallfirst            string = "C"
	EnumExecInstPegtolimit           string = "d"
	EnumExecInstPercvol              string = "D"
	EnumExecInstDni                  string = "E"
	EnumExecInstWorktostrategy       string = "e"
	EnumExecInstDnr                  string = "F"
	EnumExecInstAon                  string = "G"
	EnumExecInstRestateonsysfail     string = "H"
	EnumExecInstInstitonly           string = "I"
	EnumExecInstRestateontradinghalt string = "J"
	EnumExecInstCancelontradinghalt  string = "K"
	EnumExecInstLastpeg              string = "L"
	EnumExecInstMidprcpeg            string = "M"
	EnumExecInstNonnego              string = "N"
	EnumExecInstOpenpeg              string = "O"
	EnumExecInstMarkpeg              string = "P"
	EnumExecInstCancelonsysfail      string = "Q"
	EnumExecInstPrimpeg              string = "R"
	EnumExecInstSuspend              string = "S"
	EnumExecInstCustdispinst         string = "U"
	EnumExecInstNetting              string = "V"
	EnumExecInstPegvwap              string = "W"
	EnumExecInstTradealong           string = "X"
	EnumExecInstTrytostop            string = "Y"
	EnumExecInstCxlifnotbest         string = "Z"
)
