// Code generated by fixgen. DO NOT EDIT.

package fix44

// Enum type EnumSubscriptionRequestType
const (
	EnumSubscriptionRequestTypeSnapshot       string = "0"
	EnumSubscriptionRequestTypeSnapshotupdate string = "1"
	EnumSubscriptionRequestTypeUnsubscribe    string = "2"
)
