// Code generated by fixgen. DO NOT EDIT.

package fix44

// Enum type EnumSecurityIDSource
const (
	EnumSecurityIDSourceCusip                         string = "1"
	EnumSecurityIDSourceSedol                         string = "2"
	EnumSecurityIDSourceQuik                          string = "3"
	EnumSecurityIDSourceIsin                          string = "4"
	EnumSecurityIDSourceRic                           string = "5"
	EnumSecurityIDSourceIsocurr                       string = "6"
	EnumSecurityIDSourceIsocountry                    string = "7"
	EnumSecurityIDSourceExchsymb                      string = "8"
	EnumSecurityIDSourceCta                           string = "9"
	EnumSecurityIDSourceBlmbrg                        string = "A"
	EnumSecurityIDSourceWertpapier                    string = "B"
	EnumSecurityIDSourceDutch                         string = "C"
	EnumSecurityIDSourceValoren                       string = "D"
	EnumSecurityIDSourceSicovam                       string = "E"
	EnumSecurityIDSourceBelgian                       string = "F"
	EnumSecurityIDSourceCommon                        string = "G"
	EnumSecurityIDSourceClearinghouse                 string = "H"
	EnumSecurityIDSourceFpml                          string = "I"
	EnumSecurityIDSourceOptionpricereportingauthority string = "J"
)
