// Code generated by fixgen. DO NOT EDIT.

package fix44

// Enum type EnumMDUpdateAction
const (
	EnumMDUpdateActionNew    string = "0"
	EnumMDUpdateActionChange string = "1"
	EnumMDUpdateActionDelete string = "2"
)
